PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?Dataset ?Modified ?Publisher
WHERE {
  ?s rdf:type <http://publishmydata.com/def/dataset#Dataset>;
     rdfs:label ?Dataset;
     dcterms:publisher ?Pub;
     dcterms:modified ?Modified. 
  ?Pub rdfs:label ?Publisher.
  FILTER (?Modified > "2016-07-01T00:00:00"^^xsd:dateTime)
}

ORDER BY ?Modified
