SELECT *
WHERE {
  ?obs <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/linked-data/cube#DataSet>.
  ?obs <http://www.w3.org/2000/01/rdf-schema#label> ?Name.
  ?obs <http://purl.org/dc/terms/publisher> ?Publisher.
  
OPTIONAL{?obs <http://publishmydata.com/def/dataset#contactEmail> ?Email.}
OPTIONAL{?obs <http://publishmydata.com/def/dataset#nextUpdateDue> ?UpdateDate.}  
OPTIONAL{?obs <http://www.w3.org/2000/01/rdf-schema#comment> ?Comment.}
  
FILTER(?Publisher =  <http://statistics.gov.scot/id/organisation/nhs-information-services-division>)
}
